name: einkaufszettel
description: "Eine nützliche App"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter_platform_widgets:
  platform_icons:
  hive_ce:
  hive_ce_flutter:
  flutter_launcher_icons:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:
  hive_ce_generator:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  image_path: "assets/einkaufszettel.png"
  android: true
  ios: true

